version: '3' 
services:
    postgres:
        image: "postgres:latest"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    api:
        depends_on:
            - postgres
        image: ymouni/simpleblogapi
        build:
            dockerfile: Dockerfile.dev
            context: .
        ports:
            - '3000:3000'
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api